cider                 = "10.0.0.0/16"
region                = "us-east-1"
Name                  = "devv"
public1_subnet_cider  = "10.0.1.0/24"
public2_subnet_cider  = "10.0.2.0/24"
private1_subnet_cider = "10.0.3.0/24"
private2_subnet_cider = "10.0.4.0/24"
az1                   = "us-east-1a"
az2                   = "us-east-1b"


engine               = "mysql"
engine_version       = "5.7"
instance_class       = "db.t2.micro"
db_name              = "my_db"
#username             = "user1"
#password             = "password"
parameter_group_name = "default.mysql5.7"
port                 = "3306"

