- name: playbook
  hosts: host
  become_user: root
  become: true
  tasks:
    - name: Update  apt packages
      apt:
          update_cache: yes
          cache_valid_time: 86400 #One day   
    - name: install docker
      apt:
        name: docker.io
        state: present
    - name: install jdk
      apt:
        name: default-jdk-headless
        state: present
    - name: copy agent.jar
      copy:
        src: agent.jar
        dest: /home/ubuntu
    - name: copy env file to slave
      copy:
          src: ../.env
          dest: /home/ubuntu
    - name: running docker without sudo  
      user:
          name: "ubuntu"
          groups: docker
          append: yes